<a href="https://colab.research.google.com/github/SirigineediJahnavi/FML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
a=np.array([2,34,2])
print(type(a)) 

<class 'numpy.ndarray'>


In [52]:
import numpy as np
a=np.array([[2,3,5],[8,9,5]])
print(a.shape)
print(a[0][2])
b=np.array([2,3])
print(b.shape)Unit

(2, 3)
5
(2,)


In [54]:
import numpy as np
a=np.array([[1,2,4],[2,7,3]])
b=(a>2)
print(b)
b=a[a>2]
print(b)

[[False False  True]
 [False  True  True]]
[4 7 3]


In [31]:
import numpy as np
a=np.ones((2,3))
print(a)
b=np.full((2,2),21)
print(b)
c=np.eye(4)
print(c)
d=np.random.random((2,4))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]
[[21 21]
 [21 21]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.91835675 0.46418783 0.15035366 0.01846266]
 [0.34502931 0.09938907 0.8483405  0.65953458]]


In [45]:
import numpy as np
a=np.array([[1,3,53],[3,4,5]])
b=a[:1,:1]
print(b)
b[0,0]=21
print(a)

[[1]]
[[21  3 53]
 [ 3  4  5]]


In [49]:
import numpy as np
a=np.array([[2,34,2],[3,6,8],[5,4,6]])
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:3, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[3 6 8] (3,)
[[3 6 8]
 [5 4 6]] (2, 3)
[[3 6 8]] (1, 3)
